### ISSUE TITLE
How to remove it ?

### ISSUE THREAD

**Issue by DouglasHennrich** [caffeinalab/tiapp-composer#6]
I want to remove it since I can't create new apps because it tries to run tiapp-composer first =l

**Comment by Jei** [comment]
You can either:
- use the command `ti config paths.hooks -r <PATH TO TIAPP COMPOSER>/hooks`;
or
- edit your titanium config file (in my case it's `~/.titanium/config.json`) and remove the tiapp-composer line from the paths.hooks attribute.

I'll add a preuninstall script that does that automatically.

Before removing it, could you try to update the module and see if it solves your problem?
There was a bug that caused Titanium CLI commands to fail in some cases, I solved it in 0df9ab0306de49d44e1fdd7c98a6b44ad0c035cb.
`npm update -g tiapp-composer`

**Comment by DouglasHennrich** [comment]
I update the package but still the same problem when I tried to create a new project and install a new TiSDK version =/

I just remove it from hooks as you mentioned and works just fine, after that, I re-added to keep using your package
